build: fix build on aarch64
This patch fix build error:

cli/build/local.go:88:20: undefined: syscall.Dup2
cli/build/local.go:91:17: undefined: syscall.Dup2
cli/build/local.go:101:20: undefined: syscall.Dup2

syscall.Dup3 does not exists on darwin (OSX).
syscall.Dup2 does not exists on linux (aarch64).

So a syscall wrapper was added.

Part of #400