lint: fix linter errors in rocks tests
Without this patch a user catches an error when calling mage test:
test/integration/rocks/test_rocks.py:32:11: E275 missing whitespace after keyword
test/integration/rocks/test_rocks.py:46:11: E275 missing whitespace after keyword
test/integration/rocks/test_rocks.py:53:11: E275 missing whitespace after keyword
Error: running "python3 -m flake8 test" failed with exit code 1

In CI this linter rule is ignored.

Follow up #14